title: My Learning Journey
description: Documenting my progress in Linux+, work, and self-study.
baseurl: /linux
theme: minima
collections:
  work:
    output: true
    permalink: /work/:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag
github:
  is_project_page: true
include:
  - assets/before_boot.svg
  - assets/after_boot.svg
